name: compile

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test on ${{ matrix.config.os }} with ${{ matrix.config.cc }} and ${{ matrix.config.cxx }}.
    runs-on: ${{ matrix.config.os }}
    env:
      DIRECTORY: "cache_test"
    strategy:
      matrix:
        config:
#          - {
#            name: "Windows Latest - MSVC",
#            os: windows-latest,
#            cc: "cl", cxx: "cl",
#            extra_cmake_flags: "-G \"Visual Studio 16\"",
#          }
          - {
            name: "MacOS Latest - Clang",
            os: macos-latest,
            cc: "cc", cxx: "c++",
            extra_cmake_flags: "-DCMAKE_OSX_ARCHITECTURES=x86_64",
            build_options: "-j16",
          }

    steps:
#      - name: Cache
#        id: cache
#        uses: actions/cache@v2
#        with:
#          path: ${{ env.DIRECTORY }}
#          key: ${{ runner.os }}-repo

      - name: Checkout repository
        uses: actions/checkout@v2
#        if: steps.cache.outputs.cache-hit != 'true'
        with:
          submodules: 'recursive

      - name: Foobar
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

#      - name: Restore repository
#        if: steps.cache.outputs.cache-hit == 'true'
#        run: |
#          echo
#          echo ${{ env.GITHUB_SHA }}
#          ls -al ${{ env.GITHUB_WORKSPACE }}/${{ env.DIRECTORY }}

#      - name: Setup MSVC
#        if: runner.os == 'Windows'
#        uses: ilammy/msvc-dev-cmd@v1
#
#      - name: Setup NuGet.exe for use with actions
#        if: runner.os == 'Windows'
#        uses: NuGet/setup-nuget@v1.0.5
#
#      - name: Cache build directories
#        id: cache
#        uses: actions/cache@v2
#        with:
#          path: ${{ env.BUILD_DIR }}
#          key: ${{ runner.os }}-build_debug
#
#      - name: Setup build directories (if needed)
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: mkdir ${{ env.BUILD_DIR }}
#
#      - name: List build directory contents
#        run: ls -l ${{ env.BUILD_DIR }}
#
#      - name: CMake configure
#        run: |
#          ls -l ${{ env.BUILD_DIR }}
#          cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Debug ${{ matrix.config.extra_cmake_flags }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
#
#      - name: CMake Build (Debug)
#        run: cmake --build ${{ env.BUILD_DIR }} -- ${{ matrix.config.build_options }}
#
##      - name: Install gtest
##        uses: MarkusJx/googletest-installer@v1.1
##
##      - name: Run all tests
##        run: |
##          cd build_debug/Tests
##          ctest -C Debug
##          cd ../..