name: compile

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test on ${{ matrix.config.os }} with ${{ matrix.config.cc }} and ${{ matrix.config.cxx }}.
    runs-on: ${{ matrix.config.os }}
    env:
      BUILD_DIR: "build_debug"
    strategy:
      matrix:
        config:
#          - {
#            name: "Windows Latest - MSVC",
#            os: windows-latest,
#            cc: "cl", cxx: "cl",
#            extra_cmake_flags: "-G \"Visual Studio 16\"",
#          }
          - {
            name: "MacOS Latest - Clang",
            os: macos-latest,
            cc: "cc", cxx: "c++",
            extra_cmake_flags: "-DCMAKE_OSX_ARCHITECTURES=x86_64",
            build_options: "-j16",
          }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Sanity-check
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "BUILD_DIR: ${{ env.BUILD_DIR }}"

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%s')"

      - name: Install tree
        run: |
          brew install tree

#      - name: Setup MSVC
#        if: runner.os == 'Windows'
#        uses: ilammy/msvc-dev-cmd@v1

#      - name: Setup NuGet.exe for use with actions
#        if: runner.os == 'Windows'
#        uses: NuGet/setup-nuget@v1.0.5

      - name: Cache build directories
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ runner.os }}-foo-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-foo-

      - name: echo timestamp
        run: echo "Timestamp - ${{ steps.timestamp.outputs.timestamp }}"

      - name: List build directory contents
        run: tree ${{ env.BUILD_DIR }}

      - name: CMake configure
        run: |
         mkdir -p ${{ env.BUILD_DIR }}
         cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Debug ${{ matrix.config.extra_cmake_flags }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMake configure (again)
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Debug ${{ matrix.config.extra_cmake_flags }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMake Build (Debug)
        run: cmake --build ${{ env.BUILD_DIR }} -- ${{ matrix.config.build_options }}

      - name: List build directory contents
        run: tree ${{ env.BUILD_DIR }}

      - name: Poking around...
        run: |
          brew install tree
          ls -l $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE/..
          ls $GITHUB_WORKSPACE/../..

#      - name: Install gtest
#        uses: MarkusJx/googletest-installer@v1.1
#
#      - name: Run all tests
#        run: |
#          cd build_debug/Tests
#          ctest -C Debug
#          cd ../..